### ISSUE TITLE
Great project but missing example

### ISSUE THREAD

**Issue by orefalo** [SillyFreak/svelte-golden-layout#1]
trying to come up with a working project based on the instructions is quite cryptic.

I assume it takes senior svelte skills which I don't carry

Would you mind sharing the project behind the demo link?

Thank you

**Comment by ensko** [comment]
hi, thanks for your interest! the live demo is in fact inside this repo: [src/routes](https://github.com/SillyFreak/svelte-golden-layout/tree/main/src/routes).

It's linked at the bottom of the readme; that could definitely be more prominent. Do you have some concrete suggestions how I could improve the readme or documentation in general?
